Merge of ModelCD_branch changes into the trunk.  See the individual file logs for specifics.
svn path=/trunk/zebra/project; revision=4234

diff --git a/project/fest/proj_startup b/project/fest/proj_startup
--- a/project/fest/proj_startup
+++ b/project/fest/proj_startup
@@ -1,6 +1,7 @@
-#!/bin/csh
+#!/bin/csh -f
+# $Id: proj_startup,v 1.2 1994-12-12 20:49:17 burghart Exp $
 #
-# The fest-specific project startup file.  I expect to be run out of 
+# The fest-specific project startup file.  I expect to be sourced from 
 # the "startzeb" script.
 #
 set cdpresent=0
@@ -8,79 +9,157 @@ set cdpresent=0
 # We need to try to figure out if they have a CD mounted.
 #
 if ( ! $?CDDIR ) setenv CDDIR .
-foreach dir ( $CDDIR /cd /cdrom /zeb /cdrom/cdrom0 )
-	if ( -f $dir/.cd_index) then
-		set cdpresent=1
-		set cddir=$dir
-		setenv ZEB_CDROM $dir
-		echo " "
-		echo "CDROM found on" $dir
-		break
-	endif
-end
+#
+# If a remote data dir is already set, we don't want to change it, so no
+# sense looking for a CD
+#
+if ( ! $?REM_DATA_DIR ) then
+	foreach dir ( $CDDIR /cd /cdrom /CDROM /zeb /cdrom/cdrom0 )
+		if ( -f $dir/.cd_index) then
+			set cdpresent=1
+			set cddir=$dir
+			setenv ZEB_CDROM $dir
+			echo " "
+			echo "CD-ROM found on" $dir
+			break
+		endif
+	end
+endif
 
+if ( $?REM_DATA_DIR ) then
+	echo "Using remote data directory: $REM_DATA_DIR"
+	set iop=1
+	set cddatadir=$REM_DATA_DIR
 #
 # If, in fact, there is a CD, let's get an IOP number from them.
 #
-iop_prompt:
-if ( $cdpresent ) then
-	echo 'The following IOPs are currently mounted:'
-	echo ' '; echo -n '	'
-	(cd $cddir/data; ls -d iop*)
+else if ( $cdpresent ) then
+#
+# Figure out which disk we have
+#
+	if (-f $cddir/data/iop1/aster/stormfest.033.cdf) then
+		set legal1="[1-7]"
+		set legal2="<none>"
+		set msg='This disk has observational data from IOPs 1-7'
+		set modelcd=0
+	else if (-f $cddir/data/iop8/aster/stormfest.049.cdf) then
+		set legal1="[89]"
+		set legal2="1[0-5]"
+		set msg='This disk has observational data from IOPs 8-15'
+		set modelcd=0
+	else if (-f $cddir/data/iop16/aster/stormfest.062.cdf) then
+		set legal1="1[6-9]"
+		set legal2="20"
+		set msg='This disk has observational data from IOPs 16-20'
+		set modelcd=0
+	else if (-f $cddir/data/iop3/avnold/avnold.1992.02.09.00.grib) then
+		set legal1="[3-7]"
+		set legal2="<none>"
+		set msg='This disk has model data from IOPs 3-7'
+		set modelcd=1
+	else if (-f $cddir/data/iop10/avnold/avnold.1992.02.22.12.grib) then
+		set legal1="1[0-2]"
+		set legal2="1[6-9]"
+		set msg='This disk has model data from IOPs 10-12 and 16-19'
+		set modelcd=1
+	else
+		echo "...but it does not seem to be a STORM-FEST disk."
+		echo "Ignoring the mounted CD."
+		set cdpresent=0
+		set iop=1
+		set cddatadir=.
+		goto finish
+	endif
+#
+# Which IOP?
+#
+get_iop:
+	echo $msg
 	echo ' '
-	echo -n 'Which IOP do you want to see (number only)? '
+	echo -n 'Which IOP do you want to see (iop number or "none")? '
 	set iop=$<
 #
 # Verify it.
 #
 	switch ($iop)
-		case [67]:
-			set cddatadir=$cddir/data/iop6_7
+		case [nN]*:
+			echo 'IOP data will not be available from the CD.'
+			set cdpresent=0
+			set iop=1
+			set cddatadir=.
+			goto finish
+		case ${legal1}:
+		case ${legal2}:
 			breaksw
-		case 13:
-		case 14:
-			set cddatadir=$cddir/data/iop13_14
-			breaksw
-		case [1-9]:
-		case 1[0-9]:
-		case 20:
-			set cddatadir=$cddir/data/iop$iop
-			breaksw;
 		default:
 			echo ' '
-			echo 'Please enter an IOP number from 1-20'
+			echo "IOP $iop is not on this disk"
 			echo ' '
-			goto iop_prompt
+			goto get_iop
 	endsw
-	if (! -d $cddatadir) then
-		echo ' '
-		echo "Sorry, IOP $iop is not on this disc"
-		echo ' '
-		goto iop_prompt
+#
+# Set the data directory
+#
+	if ($iop == 6 || $iop == 7) then
+		set cddatadir=$cddir/data/iop6_7
+	else if ($iop == 13 || $iop == 14) then
+		set cddatadir=$cddir/data/iop13_14
+	else
+		set cddatadir=$cddir/data/iop$iop
 	endif
 #
-# Look for a cache file.
+# Look for a cache file for the remote data, whether model or observational.
 #
-	if ( -f cache/cache.iop$iop ) then
+#	if ( -f $cddatadir/$iop/cache.iop$iop ) then
+#		setenv REM_UNIFIED_CACHE $cddatadir/$iop/cache.iop$iop
+#		echo 'Remote cache file is' $REM_UNIFIED_CACHE
+#	else
+#		echo 'No cache file'
+#	endif
+#
+# Look for a cache file for observational data.
+#
+	if ( $modelcd && -f cache/modelcache.iop$iop ) then
+		setenv REM_UNIFIED_CACHE cache/modelcache.iop$iop
+		echo 'Remote data cache file is' $REM_UNIFIED_CACHE
+	else if ( ! $modelcd && -f cache/cache.iop$iop ) then
 		setenv REM_UNIFIED_CACHE cache/cache.iop$iop
-		echo 'Cache file is' $REM_UNIFIED_CACHE
+		echo 'Remote data cache file is' $REM_UNIFIED_CACHE
 	else
 		echo 'No cache file'
-		exit
 	endif
+
 	setenv REM_DATA_DIR $cddatadir
+	setenv REMOTE_NAME CDROM	 # for dsdwidget
 else
 	echo 'No CDROM present.'
-	set cddatadir junk
+	set iop=1
+	set cddatadir=.
 endif
+
+finish:
 
 #
 # Do some final tweaking and we're set.
 #
 if ( ! $?DEFAULT_CONFIG ) setenv DEFAULT_CONFIG model_xsect
-if ($cdpresent && -f $cddatadir/defaulttime) then
+
+#
+# Warn the user about any impending creation of data directories
+#
+if ( ! -d $DATA_DIR/avnold ) then
+	echo ' '
+	echo "The DataStore daemon will be creating platform directories"
+	echo "under $DATA_DIR when it starts up."
+	echo "Please be patient, as this can take as long as a minute."
+	echo ' '
+endif
+
+if (-f $DATA_DIR/defaulttime.iop$iop) then
+	setenv INITIAL_TIME `cat $DATA_DIR/defaulttime.iop$iop`
+else if ($cdpresent && -f $cddatadir/defaulttime) then
 	setenv INITIAL_TIME `cat $cddatadir/defaulttime`
 else
-	setenv INITIAL_TIME 9-feb-92,00:01
+	setenv INITIAL_TIME 1-feb-92,00:05
 endif
-setenv REMOTE_NAME CDROM	 # for dsdwidget
+
